POST http://localhost:3333/events
Content-Type: application/json



{
    "title": "DB palestra",
    "details": "um evento para apaixonados por database",
    "maximumAttendees": 150

}

###

POST http://localhost:3333/events/9af5ecb0-2236-4bdd-8f75-78b2869dd1b3/attendees
Content-Type: application/json

{
    "name": "Wagner Gomes",
    "email": "wagner2@gmail.com"
}


###

GET http://localhost:3333/events/9af5ecb0-2236-4bdd-8f75-78b2869dd1b3


###
GET http://localhost:3333/attendees/1/badge



